name: openrivercamlib

channels:
  - conda-forge

# note that these are the developer dependencies,
# if you only want the user dependencies, see
# install_requires in setup.py
dependencies:
  - black
  - numpy
  - opencv
  - pip
  - python=3.8
  - requests
  - scipy
  - scikit-image
  - rasterio
  - xarray
  - pyproj
  - geojson
  - geos
  - shapely
  - matplotlib
  - descartes
  - netCDF4
  - pip:
    - openpiv

